openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: Управление картами (админ)
  description: API для административного управления банковскими картами
- name: Операции над картами со стороны пользователя
  description: "API просмотра списка всех карт, пагинация по картам, расположение\
    \ запроса на блокировку карты пользователем, баланс по карте, и перевод между\
    \ своими картами пользователя"
- name: Управление пользователями (админ)
  description: API для административного управления пользователями
- name: Операции по регистрации и логину
  description: "API авторизации, регистрации, и создания новых токеновобновления и\
    \ доступа"
paths:
  /api/user/refresh-tokens:
    post:
      tags:
      - Операции по регистрации и логину
      summary: "Обновление пары токенов (обновление, доступа)"
      description: "Обновление пары токенов (обновление, доступа). Требует прав по\
        льзователя"
      operationId: refreshTokens
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefreshRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/JwtResponse'
  /api/user/login:
    post:
      tags:
      - Операции по регистрации и логину
      summary: Логин пользователя
      description: Вход в систему с помощью email и password. Не требует прав.
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JwtRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/JwtResponse'
  /api/user/cards/block-request/{cardId}:
    post:
      tags:
      - Операции над картами со стороны пользователя
      summary: Размещение запроса на блокировку карты пользователем
      operationId: blockRequest
      parameters:
      - name: cardId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /api/setup/first-admin:
    post:
      tags:
      - Операции по регистрации и логину
      summary: Регистрация первого админа в систему
      description: Регистрация первого админа в систему. Не требует прав доступа
      operationId: firstAdmin
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /api/admin/users/register:
    post:
      tags:
      - Операции по регистрации и логину
      summary: Регистрация пользователя
      description: "Регистрация пользователя по email, password и роли (USER/ADMIN).\
        \ Требует прав администрации"
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /api/admin/cards:
    post:
      tags:
      - Управление картами (админ)
      summary: Создание новой карты
      description: Создает банковскую карту для указанного пользователя. Требуются
        права администратора.
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCardRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CardResponse'
  /api/user/cards/transfer:
    patch:
      tags:
      - Операции над картами со стороны пользователя
      summary: Перевод между картами пользователя
      description: "Операция перевода между картами одного пользователя, указываем\
        \ откуда, куда, и баланс"
      operationId: transfer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /api/admin/cards/{cardId}/block:
    patch:
      tags:
      - Управление картами (админ)
      summary: Блокировка карты пользователя
      description: Блокирует указанную карту. Требуются права администратора.
      operationId: block
      parameters:
      - name: cardId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /api/admin/cards/{cardId}/activate:
    patch:
      tags:
      - Управление картами (админ)
      summary: Активация карты пользователя
      description: Активирует указанную карту. Требуются права администратора.
      operationId: activate
      parameters:
      - name: cardId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /api/admin/cards/reject-block/{requestId}:
    patch:
      tags:
      - Управление картами (админ)
      summary: Отклонение запроса на блокировку
      description: Операция отклонения запроса на блокировку указанной карты. Требуются
        права администратора.
      operationId: rejectBlock
      parameters:
      - name: requestId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /api/admin/cards/approve-block/{requestId}:
    patch:
      tags:
      - Управление картами (админ)
      summary: Одобрение запроса на блокировку
      description: Операция одобрения запроса на блокировку указанной карты. Требуются
        права администратора.
      operationId: approveBlock
      parameters:
      - name: requestId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /api/user/cards:
    get:
      tags:
      - Операции над картами со стороны пользователя
      summary: "Получение списка всех карт пользователя, пагинация"
      description: Получаем страницы информации о картах
      operationId: getUserCardPagination
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 10
      - name: status
        in: query
        required: false
        schema:
          type: string
          enum:
          - BLOCKED
          - ACTIVE
          - EXPIRED
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PageCardResponse'
  /api/user/cards/{cardId}:
    get:
      tags:
      - Операции над картами со стороны пользователя
      summary: Баланс карты
      description: Получаем информацию о балансе карты по ее ID
      operationId: cardBalance
      parameters:
      - name: cardId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: number
  /api/user/cards/all:
    get:
      tags:
      - Операции над картами со стороны пользователя
      summary: Получение списка всех карт пользователя
      description: "Получаем список ID всех карт пользователя, UUID"
      operationId: allUsersCards
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: string
                  format: uuid
  /api/admin/cards/{cardId}:
    get:
      tags:
      - Управление картами (админ)
      summary: Информация о карте
      description: Получение информации о карте по ее ID. Требуются права администратора.
      operationId: cardInfo
      parameters:
      - name: cardId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CardResponse'
    delete:
      tags:
      - Управление картами (админ)
      summary: Удаление карты пользователя
      description: Удаляет указанную карту. Требуются права администратора.
      operationId: delete
      parameters:
      - name: cardId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /api/admin/cards/allCards:
    get:
      tags:
      - Управление картами (админ)
      summary: Получение списка всех карт
      description: "Получение списка всех карт, список из ID карт (UUID). Требуютс\
        я права администратора."
      operationId: allCards
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: string
                  format: uuid
  /api/admin/cards/all-block-requests:
    get:
      tags:
      - Управление картами (админ)
      summary: Информация о всех запросах на блокировку карт
      description: "Получение информации о всех запросах на блокировку, списком. Т\
        ребуются права администратора."
      operationId: allBlockRequests
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BlockRequestResponse'
  /api/admin/users/{userId}:
    delete:
      tags:
      - Управление пользователями (админ)
      summary: Удаление пользователей
      description: Удаляет указанного пользователя по ID (UUID). Требуются права администратора.
      operationId: deleteUser
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
components:
  schemas:
    TokenRefreshRequest:
      required:
      - refreshToken
      type: object
      properties:
        refreshToken:
          type: string
    JwtResponse:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
    JwtRequest:
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    SignupRequest:
      required:
      - email
      - password
      - role
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        role:
          type: string
          enum:
          - USER
          - ADMIN
    CreateCardRequest:
      required:
      - cardNumber
      - userId
      type: object
      properties:
        cardNumber:
          maxLength: 16
          minLength: 16
          type: string
        userId:
          type: string
          format: uuid
    CardResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        maskedNumber:
          type: string
        balance:
          type: number
        expirationDate:
          type: string
          format: date
        status:
          type: string
          enum:
          - BLOCKED
          - ACTIVE
          - EXPIRED
    TransferRequest:
      required:
      - amount
      - from
      - to
      type: object
      properties:
        from:
          type: string
          format: uuid
        to:
          type: string
          format: uuid
        amount:
          type: number
    PageCardResponse:
      type: object
      properties:
        totalPages:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int64
        first:
          type: boolean
        last:
          type: boolean
        pageable:
          $ref: '#/components/schemas/PageableObject'
        numberOfElements:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        content:
          type: array
          items:
            $ref: '#/components/schemas/CardResponse'
        number:
          type: integer
          format: int32
        sort:
          type: array
          items:
            $ref: '#/components/schemas/SortObject'
        empty:
          type: boolean
    PageableObject:
      type: object
      properties:
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        paged:
          type: boolean
        unpaged:
          type: boolean
        offset:
          type: integer
          format: int64
        sort:
          type: array
          items:
            $ref: '#/components/schemas/SortObject'
    SortObject:
      type: object
      properties:
        direction:
          type: string
        nullHandling:
          type: string
        ascending:
          type: boolean
        property:
          type: string
        ignoreCase:
          type: boolean
    BlockRequestResponse:
      type: object
      properties:
        requestId:
          type: string
          format: uuid
        cardId:
          type: string
          format: uuid
        ownerId:
          type: string
          format: uuid
        status:
          type: string
          enum:
          - PENDING
          - APPROVED
          - REJECTED
